;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Nov 3 2021
; Processor: AT89C51
; Author: Rameen Zehra
; Compiler:  ASEM-51
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   100H

;====================================================================
; CODE SEGMENT
;====================================================================

       org 50H
Delay_one_sec:
      mov A, #0; 
      mov R0, #0 ; 
      mov R1, #4 ;
Delay_main:      
      INC A ; A=A+1 (1탎)
      nop ; NO OPERATION (takes 1탎)
      JNZ Delay_main; (2탎)
      INC R0; R0=R0+1 (1탎)
      CJNE R0, #0, Delay_main; (2탎)
      DEC R1; R1=R1-1 (1탎)
      CJNE R1, #0, Delay_main; (2탎)
      RET
     org   100H; main
Start:	
      ; Write your code here
       Mov P2, #0;
Toggle_Bit:
      ;CPL P2.0 ;SET Port2 Pin1 to high
      
      LCALL Delay_one_sec;
      INC P2;
      jmp Toggle_Bit
;====================================================================
      END
