;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Nov 3 2021
; Author: Rameen Zehra
; Processor: AT89C51
; Compiler:  ASEM-51 
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp 101H ; jump to MAIN
     
     org 0003h; ISR EXT0 INTERRUPT STARTS
     INC A ; increment counter
     MOV P2, A ; show counter
     RETI ; Return form Interrupt0
 
      org 0013h ; ISR EXT1 INTERRUPT STARTS
      CLR A ; counter=0
      MOV P2, A ; Show counter
      RETI; Return form Interrupt1
      
     org 101h ; MAIN
 start:
       SETB TCON.2; TCON's bit 2 set to make external interrupt 1 generate on falling edge
       SETB TCON.0; TCON's bit 0 set to make external interrupt 0 generate on falling edge

	CLR  A ; our counter
        mov P2,   #00h; our display
	mov IE, #85H ; enable external interrupts


 loop:
      jmp loop
;====================================================================
      END
      
     


